In [1]:
import matplotlib.pyplot as plt
# 그래프 한글깨짐 해결
from matplotlib import rc

rc('font', family='AppleGothic')

plt.rcParams['axes.unicode_minus'] = False

In [2]:
import pandas as pd

In [3]:
# 데이터 읽기
house = pd.read_csv('empty_train.csv')
house_answer = pd.read_csv('empty_test.csv')

In [4]:
house.head()

,Row Labels,연도,도시지역면적,비만율,유치원 원아수,초등학교 학생수,토지거래면적,혼인건수,노인 천명당 노인여가복지시설수,1인가구비율,...,대학교수,독거노인가구비율,유치원수,인구 십만명당 문화기반시설수,인구 천명당 사설학원수,주택수,초등학교수,평균연령,빈집수,빈집지수
0,강원 화천군,2016,13230291,33.8,378,1159,7131,190,11.61,43.1,...,0,9.3,14,26.65,0.76,9349,13,42.5,209,2.186650
1,충북 영동군,2017,31106651,27.8,417,1745,15329,166,18.34,34.6,...,1,15.7,16,17.91,0.84,20925,15,49.1,2657,11.267068
2,전남 해남군,2018,57390376,37.1,534,2838,29088,284,21.04,34.4,...,0,20.0,22,13.73,0.89,30404,20,50.3,4162,12.040734
3,경북 구미시,2016,185781767,27.2,10366,26891,15345,2618,8.03,30.2,...,3,3.8,99,2.62,2.01,133737,48,36.4,10869,7.516286
4,인천 강화군,2016,17306615,36.7,617,2495,9819,219,8.87,27.8,...,1,13.1,21,14.70,0.74,26660,22,50.6,3495,11.590118

In [5]:
house.shape

(615, 25)

In [6]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row Labels        615 non-null    object
 1   연도                615 non-null    int64
 2   도시지역면적            615 non-null    int64
 3   비만율               615 non-null    float64
 4   유치원 원아수           615 non-null    int64
 5   초등학교 학생수          615 non-null    int64
 6   토지거래면적            615 non-null    int64
 7   혼인건수              615 non-null    int64
 8   노인 천명당 노인여가복지시설수  615 non-null    float64
 9   1인가구비율            615 non-null    float64
 10  등록외국인 현황          615 non-null    int64
 11  유아 천명당 보육시설수      615 non-null    float64
 12  지가변동률             615 non-null    float64
 13  출생아수              615 non-null    int64
 14  학급당 학생수           615 non-null    float64
 15  대학교수              615 non-null    int64
 16  독거노인가구비율          615 non-null    float64
 17  유치원수              615 non-null    int64
 18  인구 십만명당 문화기반시설수   615 non-null    float64
 19  인구 천명당 사설학원수      615 non-null    float64
 20  주택수               615 non-null    int64
 21  초등학교수             615 non-null    int64
 22  평균연령              615 non-null    float64
 23  빈집수               615 non-null    int64
 24  빈집지수              615 non-null    float64
dtypes: float64(11), int64(13), object(1)
memory usage: 120.2+ KB

In [7]:
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor # VIF

In [8]:
house.columns

Index(['Row Labels', '연도', '도시지역면적', '비만율', '유치원 원아수', '초등학교 학생수', '토지거래면적',
       '혼인건수', '노인 천명당 노인여가복지시설수', '1인가구비율', '등록외국인 현황', '유아 천명당 보육시설수',
       '지가변동률', '출생아수', '학급당 학생수', '대학교수', '독거노인가구비율', '유치원수',
       '인구 십만명당 문화기반시설수', '인구 천명당 사설학원수', '주택수', '초등학교수', '평균연령', '빈집수',
       '빈집지수'],
      dtype='object')

In [9]:
# 데이터파악을 좀 해봅시다.

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [11]:
#데이터셋 전처리
X = house[['연도', '도시지역면적', '비만율', '유치원 원아수', '초등학교 학생수', '토지거래면적',
       '혼인건수', '노인 천명당 노인여가복지시설수', '1인가구비율', '등록외국인 현황', '유아 천명당 보육시설수',
       '지가변동률', '출생아수', '학급당 학생수', '대학교수', '독거노인가구비율', '유치원수',
       '인구 십만명당 문화기반시설수', '인구 천명당 사설학원수', '주택수', '초등학교수', '평균연령', '빈집수']]
y = house['빈집지수']

sc = StandardScaler()
X = sc.fit_transform(X)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1 , random_state=0)

In [12]:
print(len(x_train), len(x_test))

553 62

In [13]:
#VIF로 다중공산성 확인해서 제거 할 변수 제거해보기.

Xs = house[['연도', '도시지역면적', '비만율', '유치원 원아수', '초등학교 학생수', '토지거래면적',
       '혼인건수', '노인 천명당 노인여가복지시설수', '1인가구비율', '등록외국인 현황', '유아 천명당 보육시설수',
       '지가변동률', '출생아수', '학급당 학생수', '대학교수', '독거노인가구비율', '유치원수',
       '인구 십만명당 문화기반시설수', '인구 천명당 사설학원수', '주택수', '초등학교수', '평균연령', '빈집수',
       '빈집지수']]
Xs = sm.add_constant(Xs)

vif = pd.DataFrame()
vif['VIF'] = [variance_inflation_factor(Xs.values, i) for i in range(Xs.shape[1])]
vif['predictor'] = Xs.columns
vif
# 5 이상 (유의) / 10 이상 (다중공선성 있다고 판단 - 변수 제거하여 사용)

/Users/jaunnnngspc/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

             VIF         predictor
0   1.235521e+07             const
1   2.028163e+00                연도
2   2.690885e+00            도시지역면적
3   1.666501e+00               비만율
4   3.819347e+01           유치원 원아수
5   9.476390e+01          초등학교 학생수
6   3.713295e+00            토지거래면적
7   1.291628e+02              혼인건수
8   8.669478e+00  노인 천명당 노인여가복지시설수
9   3.507714e+00            1인가구비율
10  3.054031e+00          등록외국인 현황
11  1.692539e+00      유아 천명당 보육시설수
12  1.588861e+00             지가변동률
13  1.289527e+02              출생아수
14  1.306045e+01           학급당 학생수
15  2.213412e+00              대학교수
16  3.578304e+01          독거노인가구비율
17  3.880380e+01              유치원수
18  2.208125e+00   인구 십만명당 문화기반시설수
19  2.530543e+00      인구 천명당 사설학원수
20  8.963819e+01               주택수
21  3.019278e+01             초등학교수
22  3.015114e+01              평균연령
23  8.923930e+00               빈집수
24  4.884724e+00              빈집지수

## 의미없어 보임.

In [14]:
#PCA 모델 사용 및 시각화
# 전처리, 변수 값의 크기의 설명력에 영향을 미치는 것을 막기 위해 사용(데이터셋 전처리할 때 이미완료.)

In [15]:
from sklearn.decomposition import PCA
# 주성분 분석
pca = PCA(n_components=23)
pca.fit(X)

PCA(n_components=23)

In [16]:
#기존 데이터 셋이 주성분으로는 어떻게 표현 되는지 확인
p_component = pca.transform(X)
pd.DataFrame(data = p_component).head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,-3.495570,0.018433,-0.533137,0.115242,1.079396,1.164234,1.880026,-0.979396,0.115380,-0.131095,...,-0.505113,1.225458,-0.625418,0.325190,0.011881,0.218610,0.072063,-0.214837,0.078737,-0.007027
1,-3.314478,0.913410,-0.924953,-0.599301,-0.267193,0.065358,0.090432,-0.211198,-0.259022,0.153788,...,-0.418072,0.058717,-0.100301,0.043000,-0.021505,-0.002932,0.077908,0.020687,-0.007069,-0.021463
2,-3.428254,2.711457,1.047192,-0.397401,-0.443369,-1.383359,0.571571,-0.197929,-1.238711,-0.401442,...,-1.059544,-0.006481,0.484610,-0.446982,-0.070129,0.008017,-0.077235,-0.177570,-0.073124,-0.039485
3,4.796023,0.718618,-1.401444,0.810055,-0.527181,0.427445,-0.131922,-0.449694,0.225799,-0.147986,...,-0.438351,1.148414,-0.252826,-0.403774,-0.649465,-0.216007,-0.138774,0.160221,-0.060552,-0.032895
4,-2.686590,0.472356,-0.962253,0.900412,0.892926,-0.917967,1.154240,-0.802430,-1.232685,0.815107,...,0.017132,-1.129960,-0.312227,0.204213,0.136304,-0.043074,0.083500,0.283424,-0.014549,0.053173

In [17]:
# 주성분이 기존변수들로 어떻게 표현되는지 확인
abs_house = abs(pd.DataFrame(pca.components_, columns=house.columns[1:-1]))
# 음양관계 상관없이 절댓값이 클수록 영향력 업!

In [18]:
abs_house

,연도,도시지역면적,비만율,유치원 원아수,초등학교 학생수,토지거래면적,혼인건수,노인 천명당 노인여가복지시설수,1인가구비율,등록외국인 현황,...,학급당 학생수,대학교수,독거노인가구비율,유치원수,인구 십만명당 문화기반시설수,인구 천명당 사설학원수,주택수,초등학교수,평균연령,빈집수
0,0.001737,0.178999,0.077025,0.273703,0.281038,0.020398,0.273055,0.202019,0.177104,0.197010,...,0.244277,0.184990,0.237352,0.266065,0.181933,0.179729,0.280373,0.253607,0.243025,0.208033
1,0.066643,0.262999,0.210519,0.097106,0.091856,0.483812,0.043298,0.326895,0.163083,0.080304,...,0.269783,0.125593,0.269691,0.208636,0.196593,0.140049,0.078941,0.276326,0.218239,0.273209
2,0.713392,0.011738,0.428614,0.040999,0.025036,0.055111,0.046952,0.147362,0.095630,0.030066,...,0.027076,0.039857,0.061745,0.034275,0.007007,0.046297,0.001253,0.024548,0.010692,0.084014
3,0.069899,0.209739,0.322124,0.107453,0.120733,0.147989,0.204947,0.033706,0.278698,0.156212,...,0.115155,0.033561,0.132924,0.025474,0.053993,0.065609,0.151459,0.001630,0.175808,0.050541
4,0.015275,0.346897,0.296927,0.143467,0.128296,0.296342,0.203478,0.023939,0.049468,0.366039,...,0.131893,0.128180,0.013643,0.084349,0.094606,0.399904,0.102399,0.011523,0.072004,0.270832
5,0.085535,0.075891,0.183664,0.097259,0.088747,0.090665,0.034604,0.074419,0.603596,0.198464,...,0.040232,0.614509,0.044784,0.055582,0.167373,0.134609,0.061125,0.038530,0.070528,0.037322
6,0.233902,0.228143,0.348053,0.066602,0.060539,0.131591,0.010151,0.208840,0.003133,0.236154,...,0.067125,0.008943,0.343030,0.100244,0.451155,0.192769,0.103012,0.064948,0.299982,0.036648
7,0.082639,0.121476,0.247176,0.116667,0.089315,0.322885,0.025532,0.033794,0.062351,0.322420,...,0.050377,0.057086,0.017551,0.103540,0.395707,0.578027,0.076749,0.052016,0.000693,0.060977
8,0.059048,0.022355,0.326058,0.059914,0.089629,0.096046,0.019169,0.020413,0.181834,0.135894,...,0.066558,0.124719,0.026462,0.074784,0.650562,0.018453,0.029017,0.067692,0.006777,0.204220
9,0.000997,0.080561,0.070377,0.121061,0.045605,0.244882,0.028522,0.042860,0.221594,0.529434,...,0.102906,0.581817,0.003442,0.068489,0.010200,0.439974,0.067887,0.011553,0.036027,0.102103
10,0.540987,0.429941,0.420040,0.037207,0.005333,0.181473,0.047155,0.142390,0.117980,0.218121,...,0.039062,0.010545,0.063875,0.042376,0.147147,0.100311,0.073657,0.121638,0.100598,0.102936
11,0.074529,0.384264,0.080153,0.005956,0.020253,0.201688,0.076365,0.462269,0.415178,0.281173,...,0.013681,0.384878,0.016903,0.004969,0.018582,0.240682,0.090874,0.028532,0.152568,0.259038
12,0.247439,0.531326,0.224461,0.137056,0.020328,0.305503,0.014293,0.296911,0.147378,0.094518,...,0.073206,0.027485,0.144886,0.074278,0.169579,0.206517,0.065788,0.053058,0.020024,0.426363
13,0.188486,0.009840,0.011825,0.041887,0.065616,0.479241,0.104076,0.281047,0.237585,0.227714,...,0.027923,0.004308,0.105107,0.061450,0.131210,0.098001,0.006764,0.072006,0.021700,0.660205
14,0.061650,0.144366,0.036232,0.109550,0.003448,0.034487,0.076546,0.478236,0.332907,0.306111,...,0.055061,0.189816,0.283026,0.020157,0.099721,0.191514,0.052861,0.011927,0.571317,0.100359
15,0.051847,0.110196,0.104097,0.296621,0.080116,0.060640,0.402529,0.216733,0.005896,0.114258,...,0.453630,0.059349,0.188721,0.410943,0.109922,0.020129,0.183308,0.271243,0.087189,0.007974
16,0.041308,0.075034,0.031267,0.413639,0.047792,0.052609,0.280382,0.033155,0.121020,0.003995,...,0.684862,0.057633,0.286458,0.258167,0.110479,0.158328,0.080319,0.131580,0.012740,0.011686
17,0.041192,0.003432,0.004098,0.502654,0.058354,0.202154,0.045210,0.148290,0.040773,0.007882,...,0.296379,0.051992,0.022690,0.136030,0.031006,0.123204,0.145335,0.679941,0.015909,0.165999
18,0.028489,0.003366,0.006687,0.179631,0.499002,0.017783,0.321942,0.056377,0.040635,0.023357,...,0.087533,0.010250,0.160656,0.628685,0.020026,0.011303,0.243746,0.228697,0.193829,0.039459
19,0.055183,0.034589,0.015743,0.031299,0.156601,0.064019,0.054089,0.211307,0.064978,0.003645,...,0.027100,0.020257,0.491777,0.111460,0.015111,0.004208,0.539088,0.311784,0.318401,0.017275
20,0.007524,0.003596,0.007437,0.305829,0.001209,0.056654,0.011136,0.167325,0.030805,0.019380,...,0.174393,0.011204,0.462919,0.314160,0.004451,0.003457,0.416111,0.294378,0.494888,0.039148
21,0.007375,0.000514,0.001109,0.401973,0.697770,0.031906,0.242143,0.010124,0.051305,0.015600,...,0.001604,0.009973,0.073419,0.265310,0.031974,0.025759,0.363491,0.176942,0.071384,0.056277
22,0.018199,0.003385,0.000331,0.045080,0.271289,0.003586,0.633920,0.023294,0.036010,0.046174,...,0.011083,0.022363,0.080813,0.017215,0.005163,0.002313,0.344551,0.032082,0.056100,0.028199

In [19]:
import numpy as np
np.max(abs_house)

연도                  0.713392
도시지역면적              0.531326
비만율                 0.428614
유치원 원아수             0.502654
초등학교 학생수            0.697770
토지거래면적              0.483812
혼인건수                0.633920
노인 천명당 노인여가복지시설수    0.478236
1인가구비율              0.603596
등록외국인 현황            0.529434
유아 천명당 보육시설수        0.552171
지가변동률               0.474618
출생아수                0.621946
학급당 학생수             0.684862
대학교수                0.614509
독거노인가구비율            0.491777
유치원수                0.628685
인구 십만명당 문화기반시설수     0.650562
인구 천명당 사설학원수        0.578027
주택수                 0.539088
초등학교수               0.679941
평균연령                0.571317
빈집수                 0.660205
dtype: float64

## 1위) 연도..?? 2위) 초등학교 학생 수 3위) 학급당 학생수
## 4위) 빈집 수 5위) 인구 십만명당 문화 기반 시설 수 
## 6) 혼인건수 7위) 유치원 수 8위) 출생아 수 9위) 대학교수

In [20]:
#공분산과 고유벡터, 고유값으로 PCA 인자 확인하기
covaiance_matrix = np.cov([X[:,0], X[:,1],X[:,2],X[:,3],X[:,4]])
covaiance_matrix

array([[ 1.00162866,  0.02097206,  0.37126505,  0.01210708,  0.02643726],
       [ 0.02097206,  1.00162866, -0.03117597,  0.55859619,  0.55329066],
       [ 0.37126505, -0.03117597,  1.00162866, -0.20113169, -0.21836198],
       [ 0.01210708,  0.55859619, -0.20113169,  1.00162866,  0.97197772],
       [ 0.02643726,  0.55329066, -0.21836198,  0.97197772,  1.00162866]])

In [21]:
value, vector = np.linalg.eig(covaiance_matrix)

In [22]:
value[0]/sum(value)

0.4921064129272844

In [23]:
# knn regressor
from sklearn.neighbors import KNeighborsRegressor
knn_model = KNeighborsRegressor(n_neighbors=3)
knn_model.fit(x_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [24]:
print(knn_model.score(x_train, y_train))
print(knn_model.score(x_test, y_test))

y_pred_knn = knn_model.predict(x_test)
print(y_pred_knn)

0.9170774353979535
0.784474863060075
[ 1.32110363  6.27575497  9.40413753 13.15228247  1.37191387  7.16912583
  3.0316474   5.79696203  4.38736023 14.02985777  3.73000507 10.93941047
  8.75199567 12.26418367 11.70588163  7.09464287 12.37067683 13.22109587
 12.11963137  6.2159687   9.71556223  4.43010543 11.2542507   8.190937
 12.81636213 12.28864063 14.28583173  6.78716523 12.29582527  9.6353225
  2.4840257   4.51628083 12.39954943 11.31615737  7.61907993 13.08218973
  4.289229   11.62828493 12.7596725   3.78370157 11.52160213  9.86532297
 13.12811273 12.51523697  5.91337317  3.14396653 12.4921972   5.65216233
  9.11170337  5.4271968   8.61570083  5.8395743  11.43110083 12.2029591
 11.07084137  1.98434397  2.29253617 12.12299667 15.68362373 10.24650537
 10.2340582  10.3871219 ]

In [25]:
from sklearn.tree import DecisionTreeRegressor
cart = DecisionTreeRegressor(max_depth=3).fit(x_train, y_train)  # 보통 깊이 3

In [26]:
cart.feature_importances_

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.11883251, 0.06774464, 0.01648279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.62569609, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.17124397])

In [27]:
cart.score(x_test,y_test)

0.341424591547554

In [28]:
from dmba import textDecisionTree
print(textDecisionTree(cart))

no display found. Using non-interactive Agg backend
node=0 test node: go to node 1 if 15 <= -0.4058840572834015 else to node 8
  node=1 test node: go to node 2 if 7 <= -0.5470014810562134 else to node 5
    node=2 test node: go to node 3 if 22 <= -0.46971045434474945 else to node 4
      node=3 leaf node: [[1.0]]
      node=4 leaf node: [[1.0]]
    node=5 test node: go to node 6 if 9 <= -0.4329853504896164 else to node 7
      node=6 leaf node: [[1.0]]
      node=7 leaf node: [[1.0]]
  node=8 test node: go to node 9 if 22 <= -0.9648978412151337 else to node 12
    node=9 test node: go to node 10 if 22 <= -1.0560216307640076 else to node 11
      node=10 leaf node: [[1.0]]
      node=11 leaf node: [[1.0]]
    node=12 test node: go to node 13 if 8 <= -0.7767762243747711 else to node 14
      node=13 leaf node: [[1.0]]
      node=14 leaf node: [[1.0]]

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [30]:
dct_model = DecisionTreeRegressor()
dct_model.fit(x_train, y_train)
y_pred_dct = dct_model.predict(x_test)
print(y_pred_dct)
print(y_pred_dct.shape)

[ 2.2586244  6.6927043 11.0616003 12.2758047  0.6993379  8.2837289
  3.4930428  7.3356707  4.1490006 20.6720863  3.5505925 14.2845884
  7.9809471 11.5656067 13.7898539  7.5554098 12.8038898 13.6305732
 10.738455   8.8486884  7.9809471  5.4200441 11.9331402  9.159508
 12.7609136 17.4540767  9.4671277  9.7130777 12.3817296  9.6922694
  4.612601   4.7984255 11.8840416 12.3898544  9.1997698 12.0696638
  3.8227039 12.9994172 17.4540767  5.0352054 13.092476  11.1634146
 13.6305732 10.2132435  6.6844203  4.9846777 12.7620656  4.1490006
  5.0602442 10.166467  12.544005   5.1706471 10.2132435 11.465899
  9.5998369  2.7675025  6.882422   2.106089  15.1904112 11.5047417
 10.3065513 10.5897916]
(62,)

In [31]:
dct_model.score(x_test,y_test)

0.823148345927215

In [32]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor

In [33]:
bag_model = BaggingRegressor(
    DecisionTreeRegressor(),
    n_estimators= 100,
    max_samples= 0.7,
    bootstrap=True,
    n_jobs=-1
)

bag_model.fit(x_train, y_train)

BaggingRegressor(base_estimator=DecisionTreeRegressor(), max_samples=0.7,
                 n_estimators=100, n_jobs=-1)

In [34]:
bag_model.score(x_test,y_test)

0.9400834991274007

In [35]:
from sklearn.ensemble import RandomForestRegressor

rnd_model = RandomForestRegressor(
    n_estimators=100,
    max_leaf_nodes=16, #과적합 방지
    n_jobs=-1
)
rnd_model.fit(x_train,y_train)
rnd_model.score(x_test,y_test)

0.8762393815277439

In [49]:
from sklearn.ensemble import AdaBoostRegressor

ada = AdaBoostRegressor(
    DecisionTreeRegressor(),
    n_estimators=13,
    learning_rate=0.5,
)
ada.fit(x_train, y_train)
ada.score(x_test, y_test)

0.963775508902709

In [50]:
from sklearn.tree import DecisionTreeRegressor

tree_1 = DecisionTreeRegressor(max_depth = 3)
tree_1.fit(x_train, y_train)

residual_1 = y_train - tree_1.predict(x_train)
tree_2 = DecisionTreeRegressor(max_depth = 3)
tree_2.fit(x_train, residual_1)

residual_2 = residual_1 - tree_2.predict(x_train)
tree_3 = DecisionTreeRegressor(max_depth = 3)
tree_3.fit(x_train, residual_2)

DecisionTreeRegressor(max_depth=3)

In [51]:
pd.DataFrame({'y': y_test.values,
'tree_1': tree_1.predict(x_test),
'tree_2': tree_2.predict(x_test),
'tree_3': tree_3.predict(x_test),
'sum': sum([tree_1.predict(x_test),
tree_2.predict(x_test),
tree_3.predict(x_test)])})

            y     tree_1    tree_2    tree_3        sum
0    1.960505   2.449358 -0.409709  0.515539   2.555188
1    6.556912   5.631318  0.757446  0.515539   6.904303
2    8.129256  11.974725 -0.409709 -2.204523   9.360493
3   14.496582  11.974725  1.143584  0.042498  13.160807
4    0.785371   2.449358 -0.409709  0.515539   2.555188
..        ...        ...       ...       ...        ...
57   2.634307   3.074145 -0.409709  0.042498   2.706934
58  13.694844  11.974725  3.463292  0.042498  15.480516
59  10.312338  11.974725 -0.409709 -2.204523   9.360493
60  10.931669  11.974725  0.757446 -2.204523  10.527648
61  10.363342   8.426282 -0.409709  0.515539   8.532113

[62 rows x 5 columns]

In [52]:
from sklearn.ensemble import GradientBoostingRegressor
gbrt = GradientBoostingRegressor(
    max_depth=9,
    n_estimators=9,
    learning_rate=0.5
)

gbrt.fit(x_train,y_train)
gbrt.score(x_test,y_test)

0.925873242745766

In [53]:
### 학습한 모델을 테스트 데이터셋에 적용
# (1) 테스트 데이터셋에, 트레인 데이터셋과 동일하게 전처리 등 적용
x_test = house_answer[['연도', '도시지역면적', '비만율', '유치원 원아수', '초등학교 학생수', '토지거래면적',
       '혼인건수', '노인 천명당 노인여가복지시설수', '1인가구비율', '등록외국인 현황', '유아 천명당 보육시설수',
       '지가변동률', '출생아수', '학급당 학생수', '대학교수', '독거노인가구비율', '유치원수',
       '인구 십만명당 문화기반시설수', '인구 천명당 사설학원수', '주택수', '초등학교수', '평균연령', '빈집수']]
x_test_sc = sc.transform(x_test) # fit를 사용하면 안됨 트레인 데이터셋과 동일하게 할것이기 때문!

#(2) 모델 수행 결과 기록
y_pred =ada.predict(x_test_sc)

In [54]:
house_answer['빈집지수'] = y_pred
house_answer.to_csv('./answer_박정민.csv', index=False, encoding='utf-8-sig') # 한글 저장

In [55]:
# 스케일러 및 모델 저장
import joblib

joblib.dump(sc, 'house_scaler.pkl')
joblib.dump(ada, 'house_ada.pkl')

['house_ada.pkl']

In [56]:
#모델 load시 같은 결과나오는지 확인
scaler = joblib.load('house_scaler.pkl')
model = joblib.load('house_ada.pkl')

y_pred_re = model.predict(x_test_sc)
print(y_pred == y_pred_re)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True]